In [320]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [321]:
%matplotlib inline
pd.set_option('display.max_columns', None)

In [322]:
# import excel file StateGeneralbyPrecinctNov2016.xlsx
tn_2016=pd.read_excel('../data/2016_election/StateGeneralbyPrecinctNov2016.xlsx',
                      usecols=['COUNTY','PRECINCT','OFFICENAME','ELECTDATE','RNAME1','PARTY1','PVTALLY1',
                             'RNAME2','PARTY2','PVTALLY2','RNAME3','PARTY3','PVTALLY3','RNAME4','PARTY4','PVTALLY4',
                             'RNAME5','PARTY5','PVTALLY5','RNAME6','PARTY6','PVTALLY6','RNAME7','PARTY7','PVTALLY7',
                             'RNAME8','PARTY8','PVTALLY8','RNAME9','PARTY9','PVTALLY9','RNAME10','PARTY10','PVTALLY10'])
tn_2016

,COUNTY,PRECINCT,OFFICENAME,ELECTDATE,RNAME1,PARTY1,PVTALLY1,RNAME2,PARTY2,PVTALLY2,RNAME3,PARTY3,PVTALLY3,RNAME4,PARTY4,PVTALLY4,RNAME5,PARTY5,PVTALLY5,RNAME6,PARTY6,PVTALLY6,RNAME7,PARTY7,PVTALLY7,RNAME8,PARTY8,PVTALLY8,RNAME9,PARTY9,PVTALLY9,RNAME10,PARTY10,PVTALLY10
0,Anderson,Andersonville,United States President,2016-11-08,Donald J. Trump,Republican,1222,Hillary Clinton,Democratic,227.0,"""Rocky"" Roque De La Fuente",Independent,2.0,Gary Johnson,Independent,32.0,Alyson Kennedy,Independent,1.0,Mike Smith,Independent,7.0,Jill Stein,Independent,5.0,Write-In - Darrell L. Castle,NaN,1.0,Write-In - Cherunda Fox,NaN,0.0,Write-In - Tom Hoefling,NaN,0.0
1,Anderson,Andersonville,United States President,2016-11-08,Write-In - Kyle Kenley Kopitke,NaN,0,Write-In - Laurence Kotlikoff,NaN,0.0,Write-In - David Limbaugh,NaN,0.0,Write-In - Evan McMullin,NaN,3.0,Write-In - Marshall Schoenke,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Anderson,Andersonville,United States House of Representatives District 3,2016-11-08,Chuck Fleischmann,Republican,1124,Melody Shekari,Democratic,195.0,Topher Kersting,Independent,21.0,Cassandra Mitchell,Independent,36.0,Rick Tyler,Independent,30.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Anderson,Andersonville,Tennessee House of Representatives District 36,2016-11-08,Dennis H. Powers,Republican,1128,Bob Fannon,Democratic,265.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Anderson,Briceville,United States President,2016-11-08,Donald J. Trump,Republican,243,Hillary Clinton,Democratic,42.0,"""Rocky"" Roque De La Fuente",Independent,3.0,Gary Johnson,Independent,5.0,Alyson Kennedy,Independent,0.0,Mike Smith,Independent,1.0,Jill Stein,Independent,0.0,Write-In - Darrell L. Castle,NaN,0.0,Write-In - Cherunda Fox,NaN,0.0,Write-In - Tom Hoefling,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9397,Wilson,Absentee,United States President,2016-11-08,Donald J. Trump,Republican,661,Hillary Clinton,Democratic,397.0,"""Rocky"" Roque De La Fuente",Independent,4.0,Gary Johnson,Independent,47.0,Alyson Kennedy,Independent,3.0,Mike Smith,Independent,9.0,Jill Stein,Independent,7.0,Write-In - Darrell L. Castle,Independent,0.0,Write-In - Cherunda Fox,Independent,0.0,Write-In - Tom Hoefling,Independent,0.0
9398,Wilson,Absentee,United States President,2016-11-08,Write-In - Kyle Kenley Kopitke,Independent,0,Write-In - Laurence Kotlikoff,Independent,0.0,Write-In - David Limbaugh,Independent,0.0,Write-In - Evan McMullin,Independent,14.0,Write-In - Marshall Schoenke,Independent,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9399,Wilson,Absentee,United States House of Representatives District 6,2016-11-08,Diane Black,Republican,699,David W. Kent,Democratic,297.0,David Ross,Independent,71.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9400,Wilson,Absentee,Tennessee House of Representatives District 46,2016-11-08,Mark Pody,Republican,264,Amelia Morrison Hipps,Democratic,142.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9401,Wilson,Absentee,Tennessee House of Representatives District 57,2016-11-08,Susan M Lynn,Republican,432,Trisha Farmer,Democratic,219.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [323]:
tn_2016.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9402 entries, 0 to 9401
Data columns (total 34 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   COUNTY      9402 non-null   object
 1   PRECINCT    9402 non-null   object
 2   OFFICENAME  9402 non-null   object
 3   ELECTDATE   9402 non-null   object
 4   RNAME1      9402 non-null   object
 5   PARTY1      7561 non-null   object
 6   PVTALLY1    9402 non-null   int64
 7   RNAME2      7984 non-null   object
 8   PARTY2      6088 non-null   object
 9   PVTALLY2    7984 non-null   float64
 10  RNAME3      5738 non-null   object
 11  PARTY3      3787 non-null   object
 12  PVTALLY3    5738 non-null   float64
 13  RNAME4      4913 non-null   object
 14  PARTY4      2726 non-null   object
 15  PVTALLY4    4913 non-null   float64
 16  RNAME5      4567 non-null   object
 17  PARTY5      2726 non-null   object
 18  PVTALLY5    4567 non-null   float64
 19  RNAME6      2269 non-null   object
 20  PARTY6      2269 non-null   object
 21  PVTALLY6    2269 non-null   float64
 22  RNAME7      2269 non-null   object
 23  PARTY7      2269 non-null   object
 24  PVTALLY7    2269 non-null   float64
 25  RNAME8      2022 non-null   object
 26  PARTY8      181 non-null    object
 27  PVTALLY8    2022 non-null   float64
 28  RNAME9      2022 non-null   object
 29  PARTY9      181 non-null    object
 30  PVTALLY9    2022 non-null   float64
 31  RNAME10     2022 non-null   object
 32  PARTY10     181 non-null    object
 33  PVTALLY10   2022 non-null   float64
dtypes: float64(9), int64(1), object(24)
memory usage: 2.4+ MB

In [324]:
# merge entries in all RNAME columns into new column "name"
tn_2016_namemelt=tn_2016.melt(id_vars=['COUNTY','PRECINCT','OFFICENAME','ELECTDATE'],value_vars=['RNAME1','RNAME2','RNAME3','RNAME4','RNAME5','RNAME6','RNAME7','RNAME8','RNAME9','RNAME10'],value_name="name")
# drop column "variable" created by .melt
tn_2016_namemelt=tn_2016_namemelt.drop(['variable'],axis=1)                          
tn_2016_namemelt.head(9405)

,COUNTY,PRECINCT,OFFICENAME,ELECTDATE,name
0,Anderson,Andersonville,United States President,2016-11-08,Donald J. Trump
1,Anderson,Andersonville,United States President,2016-11-08,Write-In - Kyle Kenley Kopitke
2,Anderson,Andersonville,United States House of Representatives District 3,2016-11-08,Chuck Fleischmann
3,Anderson,Andersonville,Tennessee House of Representatives District 36,2016-11-08,Dennis H. Powers
4,Anderson,Briceville,United States President,2016-11-08,Donald J. Trump
...,...,...,...,...,...
9400,Wilson,Absentee,Tennessee House of Representatives District 46,2016-11-08,Mark Pody
9401,Wilson,Absentee,Tennessee House of Representatives District 57,2016-11-08,Susan M Lynn
9402,Anderson,Andersonville,United States President,2016-11-08,Hillary Clinton
9403,Anderson,Andersonville,United States President,2016-11-08,Write-In - Laurence Kotlikoff
9404,Anderson,Andersonville,United States House of Representatives District 3,2016-11-08,Melody Shekari

In [325]:
# merge entries in all PARTY columns into new column "party"
tn_2016_partymelt=tn_2016.melt(id_vars=['COUNTY','PRECINCT','OFFICENAME','ELECTDATE'],value_vars=['PARTY1','PARTY2','PARTY3','PARTY4','PARTY5','PARTY6','PARTY7','PARTY8','PARTY9','PARTY10'],value_name="party")
# drop column "variable" created by .melt
tn_2016_partymelt=tn_2016_partymelt.drop(['variable'],axis=1)
tn_2016_partymelt.head(9405)

,COUNTY,PRECINCT,OFFICENAME,ELECTDATE,party
0,Anderson,Andersonville,United States President,2016-11-08,Republican
1,Anderson,Andersonville,United States President,2016-11-08,NaN
2,Anderson,Andersonville,United States House of Representatives District 3,2016-11-08,Republican
3,Anderson,Andersonville,Tennessee House of Representatives District 36,2016-11-08,Republican
4,Anderson,Briceville,United States President,2016-11-08,Republican
...,...,...,...,...,...
9400,Wilson,Absentee,Tennessee House of Representatives District 46,2016-11-08,Republican
9401,Wilson,Absentee,Tennessee House of Representatives District 57,2016-11-08,Republican
9402,Anderson,Andersonville,United States President,2016-11-08,Democratic
9403,Anderson,Andersonville,United States President,2016-11-08,NaN
9404,Anderson,Andersonville,United States House of Representatives District 3,2016-11-08,Democratic

In [326]:
# merge entries in all PVTALLY columns into new column "vote_count"
tn_2016_pvtallymelt=tn_2016.melt(id_vars=['COUNTY','PRECINCT','OFFICENAME','ELECTDATE'],value_vars=['PVTALLY1','PVTALLY2','PVTALLY3','PVTALLY4','PVTALLY5','PVTALLY6','PVTALLY7','PVTALLY8','PVTALLY9','PVTALLY10'],value_name="vote_count")
# drop column "variable" created by .melt
tn_2016_pvtallymelt=tn_2016_pvtallymelt.drop(['variable'],axis=1)
tn_2016_pvtallymelt.head(9405)

,COUNTY,PRECINCT,OFFICENAME,ELECTDATE,vote_count
0,Anderson,Andersonville,United States President,2016-11-08,1222.0
1,Anderson,Andersonville,United States President,2016-11-08,0.0
2,Anderson,Andersonville,United States House of Representatives District 3,2016-11-08,1124.0
3,Anderson,Andersonville,Tennessee House of Representatives District 36,2016-11-08,1128.0
4,Anderson,Briceville,United States President,2016-11-08,243.0
...,...,...,...,...,...
9400,Wilson,Absentee,Tennessee House of Representatives District 46,2016-11-08,264.0
9401,Wilson,Absentee,Tennessee House of Representatives District 57,2016-11-08,432.0
9402,Anderson,Andersonville,United States President,2016-11-08,227.0
9403,Anderson,Andersonville,United States President,2016-11-08,0.0
9404,Anderson,Andersonville,United States House of Representatives District 3,2016-11-08,195.0

In [327]:
# add "party" column to tn_2016_namemelt
party=tn_2016_partymelt['party']
tn_2016_namemelt=tn_2016_namemelt.join(party)
tn_2016_namemelt.head(3)

,COUNTY,PRECINCT,OFFICENAME,ELECTDATE,name,party
0,Anderson,Andersonville,United States President,2016-11-08,Donald J. Trump,Republican
1,Anderson,Andersonville,United States President,2016-11-08,Write-In - Kyle Kenley Kopitke,NaN
2,Anderson,Andersonville,United States House of Representatives District 3,2016-11-08,Chuck Fleischmann,Republican

In [328]:
# add "vote_count" column to tn_2016_namemelt
pvtally=tn_2016_pvtallymelt['vote_count']
tn_2016_namemelt=tn_2016_namemelt.join(pvtally)
tn_2016_namemelt.head(3)

,COUNTY,PRECINCT,OFFICENAME,ELECTDATE,name,party,vote_count
0,Anderson,Andersonville,United States President,2016-11-08,Donald J. Trump,Republican,1222.0
1,Anderson,Andersonville,United States President,2016-11-08,Write-In - Kyle Kenley Kopitke,NaN,0.0
2,Anderson,Andersonville,United States House of Representatives District 3,2016-11-08,Chuck Fleischmann,Republican,1124.0

In [329]:
tn_2016_namemelt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 94020 entries, 0 to 94019
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   COUNTY      94020 non-null  object
 1   PRECINCT    94020 non-null  object
 2   OFFICENAME  94020 non-null  object
 3   ELECTDATE   94020 non-null  object
 4   name        43208 non-null  object
 5   party       27969 non-null  object
 6   vote_count  43208 non-null  float64
dtypes: float64(1), object(6)
memory usage: 5.0+ MB

In [330]:
# lower case column names
tn_2016_namemelt.columns=tn_2016_namemelt.columns.str.lower()
tn_2016_namemelt.head(2)

,county,precinct,officename,electdate,name,party,vote_count
0,Anderson,Andersonville,United States President,2016-11-08,Donald J. Trump,Republican,1222.0
1,Anderson,Andersonville,United States President,2016-11-08,Write-In - Kyle Kenley Kopitke,NaN,0.0

In [331]:
# change null values in "party" column to "no party"
tn_2016_namemelt['party'].fillna("No party", inplace = True)
tn_2016_namemelt.head(2)

,county,precinct,officename,electdate,name,party,vote_count
0,Anderson,Andersonville,United States President,2016-11-08,Donald J. Trump,Republican,1222.0
1,Anderson,Andersonville,United States President,2016-11-08,Write-In - Kyle Kenley Kopitke,No party,0.0

In [332]:
tn_2016_namemelt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 94020 entries, 0 to 94019
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   county      94020 non-null  object
 1   precinct    94020 non-null  object
 2   officename  94020 non-null  object
 3   electdate   94020 non-null  object
 4   name        43208 non-null  object
 5   party       94020 non-null  object
 6   vote_count  43208 non-null  float64
dtypes: float64(1), object(6)
memory usage: 5.0+ MB

In [333]:
# change null values in "vote_count" column to "0"
tn_2016_namemelt['vote_count'].fillna(0)

0        1222.0
1           0.0
2        1124.0
3        1128.0
4         243.0
          ...
94015       0.0
94016       0.0
94017       0.0
94018       0.0
94019       0.0
Name: vote_count, Length: 94020, dtype: float64

In [334]:
tn_2016_namemelt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 94020 entries, 0 to 94019
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   county      94020 non-null  object
 1   precinct    94020 non-null  object
 2   officename  94020 non-null  object
 3   electdate   94020 non-null  object
 4   name        43208 non-null  object
 5   party       94020 non-null  object
 6   vote_count  43208 non-null  float64
dtypes: float64(1), object(6)
memory usage: 5.0+ MB

### 43208 non-null names and 43208 non-null vote counts
### Do the nulls in "name" correlate one to one with "no party"?

In [335]:
tn_2016_namemelt[tn_2016_namemelt['name'].isna()]

,county,precinct,officename,electdate,name,party,vote_count
9573,Benton,1 Holladay,Tennessee Senate District 24,2016-11-08,NaN,No party,NaN
9578,Benton,2 Camden Jr High,Tennessee Senate District 24,2016-11-08,NaN,No party,NaN
9583,Benton,3 Camden City Hall,Tennessee Senate District 24,2016-11-08,NaN,No party,NaN
9588,Benton,4 Camden Elementary,Tennessee Senate District 24,2016-11-08,NaN,No party,NaN
9593,Benton,5 Library,Tennessee Senate District 24,2016-11-08,NaN,No party,NaN
...,...,...,...,...,...,...,...
94014,Wilson,Provisional,Tennessee House of Representatives District 57,2016-11-08,NaN,No party,NaN
94016,Wilson,Absentee,United States President,2016-11-08,NaN,No party,NaN
94017,Wilson,Absentee,United States House of Representatives District 6,2016-11-08,NaN,No party,NaN
94018,Wilson,Absentee,Tennessee House of Representatives District 46,2016-11-08,NaN,No party,NaN
94019,Wilson,Absentee,Tennessee House of Representatives District 57,2016-11-08,NaN,No party,NaN

In [336]:
tn_2016_namemelt[tn_2016_namemelt['name'].isna()].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 50812 entries, 9573 to 94019
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   county      50812 non-null  object
 1   precinct    50812 non-null  object
 2   officename  50812 non-null  object
 3   electdate   50812 non-null  object
 4   name        0 non-null      object
 5   party       50812 non-null  object
 6   vote_count  0 non-null      float64
dtypes: float64(1), object(6)
memory usage: 3.1+ MB

### Looks safe to drop rows with no votes tallied

In [337]:
# drop rows with no name and vote count
tn_2016_final=tn_2016_namemelt.dropna()

In [338]:
tn_2016_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 43208 entries, 0 to 94015
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   county      43208 non-null  object
 1   precinct    43208 non-null  object
 2   officename  43208 non-null  object
 3   electdate   43208 non-null  object
 4   name        43208 non-null  object
 5   party       43208 non-null  object
 6   vote_count  43208 non-null  float64
dtypes: float64(1), object(6)
memory usage: 2.6+ MB

In [339]:
# convert vote_count data from float64 to int 32 to to drop ".0"
tn_2016_final=tn_2016_final.astype({'vote_count':'int32'})
tn_2016_final

,county,precinct,officename,electdate,name,party,vote_count
0,Anderson,Andersonville,United States President,2016-11-08,Donald J. Trump,Republican,1222
1,Anderson,Andersonville,United States President,2016-11-08,Write-In - Kyle Kenley Kopitke,No party,0
2,Anderson,Andersonville,United States House of Representatives District 3,2016-11-08,Chuck Fleischmann,Republican,1124
3,Anderson,Andersonville,Tennessee House of Representatives District 36,2016-11-08,Dennis H. Powers,Republican,1128
4,Anderson,Briceville,United States President,2016-11-08,Donald J. Trump,Republican,243
...,...,...,...,...,...,...,...
93997,Wilson,24-1,United States President,2016-11-08,Write-In - Tom Hoefling,Independent,0
94001,Wilson,25-1,United States President,2016-11-08,Write-In - Tom Hoefling,Independent,0
94005,Wilson,25-2,United States President,2016-11-08,Write-In - Tom Hoefling,Independent,0
94010,Wilson,Provisional,United States President,2016-11-08,Write-In - Tom Hoefling,Independent,0
94015,Wilson,Absentee,United States President,2016-11-08,Write-In - Tom Hoefling,Independent,0

In [340]:
tn_2016_final.dtypes

county        object
precinct      object
officename    object
electdate     object
name          object
party         object
vote_count     int32
dtype: object

In [341]:
tn_2016_final['officename'].value_counts()

United States President                              30330
United States House of Representatives District 8     1729
United States House of Representatives District 3     1380
United States House of Representatives District 1      868
United States House of Representatives District 7      852
                                                     ...
Tennessee House of Representatives District 99          12
Tennessee House of Representatives District 1           11
Tennessee House of Representatives District 68          11
Tennessee House of Representatives District 24          10
Tennessee House of Representatives District 16          10
Name: officename, Length: 125, dtype: int64

In [342]:
tn_2016_final['officename'].unique()

array(['United States President',
       'United States House of Representatives District 3',
       'Tennessee House of Representatives District 36',
       'Tennessee House of Representatives District 33',
       'United States House of Representatives District 4',
       'Tennessee Senate District 14',
       'Tennessee House of Representatives District 62',
       'United States House of Representatives District 7',
       'Tennessee Senate District 24',
       'Tennessee House of Representatives District 75',
       'United States House of Representatives District 8',
       'Tennessee House of Representatives District 31',
       'United States House of Representatives District 2',
       'Tennessee Senate District 2',
       'Tennessee House of Representatives District 8',
       'Tennessee House of Representatives District 20',
       'Tennessee Senate District 10',
       'Tennessee House of Representatives District 24',
       'Tennessee House of Representatives District 22',
       'Tennessee Senate District 12',
       'United States House of Representatives District 6',
       'Tennessee House of Representatives District 46',
       'Tennessee House of Representatives District 79',
       'Tennessee House of Representatives District 76',
       'United States House of Representatives District 1',
       'Tennessee Senate District 4',
       'Tennessee House of Representatives District 4',
       'Tennessee House of Representatives District 3',
       'United States House of Representatives District 5',
       'Tennessee House of Representatives District 78',
       'Tennessee Senate District 26',
       'Tennessee House of Representatives District 72',
       'Tennessee Senate District 8',
       'Tennessee House of Representatives District 35',
       'Tennessee House of Representatives District 38',
       'Tennessee House of Representatives District 11',
       'Tennessee Senate District 16',
       'Tennessee House of Representatives District 47',
       'Tennessee House of Representatives District 82',
       'Tennessee House of Representatives District 25',
       'Tennessee Senate District 20',
       'Tennessee House of Representatives District 50',
       'Tennessee House of Representatives District 54',
       'Tennessee House of Representatives District 58',
       'Tennessee House of Representatives District 56',
       'Tennessee House of Representatives District 53',
       'Tennessee House of Representatives District 51',
       'Tennessee House of Representatives District 52',
       'Tennessee Senate District 18',
       'Tennessee House of Representatives District 60',
       'Tennessee House of Representatives District 59',
       'Tennessee House of Representatives District 55',
       'Tennessee House of Representatives District 40',
       'Tennessee House of Representatives District 69',
       'Tennessee House of Representatives District 77',
       'Tennessee House of Representatives District 94',
       'Tennessee House of Representatives District 41',
       'Tennessee House of Representatives District 39',
       'Tennessee House of Representatives District 92',
       'Tennessee Senate District 28',
       'Tennessee House of Representatives District 70',
       'Tennessee House of Representatives District 5',
       'Tennessee House of Representatives District 43',
       'Tennessee House of Representatives District 10',
       'Tennessee House of Representatives District 29',
       'Tennessee House of Representatives District 28',
       'Tennessee House of Representatives District 27',
       'Tennessee House of Representatives District 30',
       'Tennessee House of Representatives District 26',
       'Tennessee House of Representatives District 9',
       'Tennessee House of Representatives District 80',
       'Tennessee House of Representatives District 71',
       'Tennessee Senate District 22',
       'Tennessee House of Representatives District 74',
       'Tennessee House of Representatives District 17',
       'Tennessee House of Representatives District 15',
       'Tennessee Senate District 6',
       'Tennessee House of Representatives District 13',
       'Tennessee House of Representatives District 89',
       'Tennessee House of Representatives District 19',
       'Tennessee House of Representatives District 16',
       'Tennessee House of Representatives District 18',
       'Tennessee House of Representatives District 14',
       'Tennessee House of Representatives District 21',
       'Tennessee House of Representatives District 32',
       'Tennessee House of Representatives District 73',
       'Tennessee House of Representatives District 64',
       'Tennessee House of Representatives District 23',
       'Tennessee House of Representatives District 68',
       'Tennessee House of Representatives District 67',
       'Tennessee House of Representatives District 42',
       'Tennessee House of Representatives District 66',
       'Tennessee House of Representatives District 37',
       'Tennessee House of Representatives District 49',
       'Tennessee House of Representatives District 48',
       'Tennessee House of Representatives District 34',
       'Tennessee House of Representatives District 12',
       'United States House of Representatives District 9',
       'Tennessee House of Representatives District 86',
       'Tennessee House of Representatives District 90',
       'Tennessee Senate District 30',
       'Tennessee House of Representatives District 88',
       'Tennessee House of Representatives District 91',
       'Tennessee House of Representatives District 98',
       'Tennessee House of Representatives District 93',
       'Tennessee House of Representatives District 87',
       'Tennessee House of Representatives District 97',
       'Tennessee House of Representatives District 83',
       'Tennessee House of Representatives District 84',
       'Tennessee House of Representatives District 85',
       'Tennessee Senate District 32',
       'Tennessee House of Representatives District 96',
       'Tennessee House of Representatives District 99',
       'Tennessee House of Representatives District 95',
       'Tennessee House of Representatives District 1',
       'Tennessee House of Representatives District 2',
       'Tennessee House of Representatives District 44',
       'Tennessee House of Representatives District 45',
       'Tennessee House of Representatives District 81',
       'Tennessee House of Representatives District 6',
       'Tennessee House of Representatives District 7',
       'Tennessee House of Representatives District 65',
       'Tennessee House of Representatives District 63',
       'Tennessee House of Representatives District 61',
       'Tennessee House of Representatives District 57'], dtype=object)

In [343]:
# create data frame tn_2016_pres for presidental election
tn_2016_pres=tn_2016_final[tn_2016_final['officename'].str.match('United States President')]
tn_2016_pres=tn_2016_pres.reset_index()
tn_2016_pres

,index,county,precinct,officename,electdate,name,party,vote_count
0,0,Anderson,Andersonville,United States President,2016-11-08,Donald J. Trump,Republican,1222
1,1,Anderson,Andersonville,United States President,2016-11-08,Write-In - Kyle Kenley Kopitke,No party,0
2,4,Anderson,Briceville,United States President,2016-11-08,Donald J. Trump,Republican,243
3,5,Anderson,Briceville,United States President,2016-11-08,Write-In - Kyle Kenley Kopitke,No party,0
4,8,Anderson,Bull Run,United States President,2016-11-08,Donald J. Trump,Republican,1397
...,...,...,...,...,...,...,...,...
30325,93997,Wilson,24-1,United States President,2016-11-08,Write-In - Tom Hoefling,Independent,0
30326,94001,Wilson,25-1,United States President,2016-11-08,Write-In - Tom Hoefling,Independent,0
30327,94005,Wilson,25-2,United States President,2016-11-08,Write-In - Tom Hoefling,Independent,0
30328,94010,Wilson,Provisional,United States President,2016-11-08,Write-In - Tom Hoefling,Independent,0
30329,94015,Wilson,Absentee,United States President,2016-11-08,Write-In - Tom Hoefling,Independent,0

In [344]:
tn_2016_pres['vote_count'].value_counts()

0       16240
1        2257
2        1548
3        1074
4         805
        ...
1959        1
1927        1
1951        1
1831        1
1847        1
Name: vote_count, Length: 1484, dtype: int64

### 16240 rows have a vote count of 0. Drop those rows

In [345]:
tn_2016_pres=tn_2016_pres[tn_2016_pres['vote_count'] != 0]
tn_2016_pres=tn_2016_pres.reset_index()

In [346]:
# group county precincts into county per candidate 
tn_2016_pres=tn_2016_pres.groupby(['officename','county','name','party'], as_index=False)['vote_count'].sum()
tn_2016_pres

,officename,county,name,party,vote_count
0,United States President,Anderson,"""Rocky"" Roque De La Fuente",Independent,74
1,United States President,Anderson,Alyson Kennedy,Independent,42
2,United States President,Anderson,Donald J. Trump,Republican,19212
3,United States President,Anderson,Gary Johnson,Independent,1034
4,United States President,Anderson,Hillary Clinton,Democratic,9013
...,...,...,...,...,...
884,United States President,Wilson,Mike Smith,Independent,207
885,United States President,Wilson,Write-In - Darrell L. Castle,Independent,23
886,United States President,Wilson,Write-In - Evan McMullin,Independent,280
887,United States President,Wilson,Write-In - Laurence Kotlikoff,Independent,1
888,United States President,Wilson,Write-In - Tom Hoefling,Independent,6

In [347]:
tn_2016_pres.head(20)

,officename,county,name,party,vote_count
0,United States President,Anderson,"""Rocky"" Roque De La Fuente",Independent,74
1,United States President,Anderson,Alyson Kennedy,Independent,42
2,United States President,Anderson,Donald J. Trump,Republican,19212
3,United States President,Anderson,Gary Johnson,Independent,1034
4,United States President,Anderson,Hillary Clinton,Democratic,9013
5,United States President,Anderson,Jill Stein,Independent,189
6,United States President,Anderson,Mike Smith,Independent,174
7,United States President,Anderson,Write-In - Darrell L. Castle,No party,28
8,United States President,Anderson,Write-In - Evan McMullin,No party,115
9,United States President,Bedford,"""Rocky"" Roque De La Fuente",Independent,25
10,United States President,Bedford,Alyson Kennedy,Independent,8
11,United States President,Bedford,Donald J. Trump,Republican,11486
12,United States President,Bedford,Gary Johnson,Independent,306
13,United States President,Bedford,Hillary Clinton,Democratic,3395
14,United States President,Bedford,Jill Stein,Independent,75
15,United States President,Bedford,Mike Smith,Independent,47
16,United States President,Bedford,Write-In - Darrell L. Castle,No party,5
17,United States President,Bedford,Write-In - Evan McMullin,No party,8
18,United States President,Benton,"""Rocky"" Roque De La Fuente",Independent,12
19,United States President,Benton,Alyson Kennedy,Independent,13

### Add column that has total vote count by count for use in calculating county vote percentages

In [348]:
tn_2016_pres['sum_county_vote']=tn_2016_pres.groupby(['vote_count'])['vote_count'].sum
tn_2016_pres

,officename,county,name,party,vote_count,sum_county_vote
0,United States President,Anderson,"""Rocky"" Roque De La Fuente",Independent,74,<bound method GroupBy.sum of <pandas.core.grou...
1,United States President,Anderson,Alyson Kennedy,Independent,42,<bound method GroupBy.sum of <pandas.core.grou...
2,United States President,Anderson,Donald J. Trump,Republican,19212,<bound method GroupBy.sum of <pandas.core.grou...
3,United States President,Anderson,Gary Johnson,Independent,1034,<bound method GroupBy.sum of <pandas.core.grou...
4,United States President,Anderson,Hillary Clinton,Democratic,9013,<bound method GroupBy.sum of <pandas.core.grou...
...,...,...,...,...,...,...
884,United States President,Wilson,Mike Smith,Independent,207,<bound method GroupBy.sum of <pandas.core.grou...
885,United States President,Wilson,Write-In - Darrell L. Castle,Independent,23,<bound method GroupBy.sum of <pandas.core.grou...
886,United States President,Wilson,Write-In - Evan McMullin,Independent,280,<bound method GroupBy.sum of <pandas.core.grou...
887,United States President,Wilson,Write-In - Laurence Kotlikoff,Independent,1,<bound method GroupBy.sum of <pandas.core.grou...
888,United States President,Wilson,Write-In - Tom Hoefling,Independent,6,<bound method GroupBy.sum of <pandas.core.grou...

In [349]:
filter=tn_2016_pres['county']==tn_2016_pres['county']
tn_2016_pres['sum_county_vote']=tn_2016_pres.where(filter).sum
tn_2016_pres

RecursionError: maximum recursion depth exceeded while calling a Python object

RecursionError: maximum recursion depth exceeded while calling a Python object

In [350]:
# create new dataframe "county_vote" to use to find sum of votes per county
county_vote=tn_2016_pres.loc[0:,['county','vote_count']]
county_vote

       county  vote_count
0    Anderson          74
1    Anderson          42
2    Anderson       19212
3    Anderson        1034
4    Anderson        9013
..        ...         ...
884    Wilson         207
885    Wilson          23
886    Wilson         280
887    Wilson           1
888    Wilson           6

[889 rows x 2 columns]

In [351]:
# sum votes per county
county_vote_sum=county_vote.groupby(['county'])['vote_count'].sum()
county_vote_sum

county
Anderson       29881
Bedford        15355
Benton          6328
Bledsoe         4664
Blount         52208
               ...
Wayne           5857
Weakley        12184
White           9825
Williamson    106271
Wilson         56734
Name: vote_count, Length: 95, dtype: int32

In [352]:
# use "county_vote_sum" to add column "sum_county_vote" to tn_2016_pres correlating with value in each row
tn_2016_pres['sum_county_vote']=tn_2016_pres['county'].map(county_vote_sum)
tn_2016_pres.head(20)

,officename,county,name,party,vote_count,sum_county_vote
0,United States President,Anderson,"""Rocky"" Roque De La Fuente",Independent,74,29881
1,United States President,Anderson,Alyson Kennedy,Independent,42,29881
2,United States President,Anderson,Donald J. Trump,Republican,19212,29881
3,United States President,Anderson,Gary Johnson,Independent,1034,29881
4,United States President,Anderson,Hillary Clinton,Democratic,9013,29881
5,United States President,Anderson,Jill Stein,Independent,189,29881
6,United States President,Anderson,Mike Smith,Independent,174,29881
7,United States President,Anderson,Write-In - Darrell L. Castle,No party,28,29881
8,United States President,Anderson,Write-In - Evan McMullin,No party,115,29881
9,United States President,Bedford,"""Rocky"" Roque De La Fuente",Independent,25,15355
10,United States President,Bedford,Alyson Kennedy,Independent,8,15355
11,United States President,Bedford,Donald J. Trump,Republican,11486,15355
12,United States President,Bedford,Gary Johnson,Independent,306,15355
13,United States President,Bedford,Hillary Clinton,Democratic,3395,15355
14,United States President,Bedford,Jill Stein,Independent,75,15355
15,United States President,Bedford,Mike Smith,Independent,47,15355
16,United States President,Bedford,Write-In - Darrell L. Castle,No party,5,15355
17,United States President,Bedford,Write-In - Evan McMullin,No party,8,15355
18,United States President,Benton,"""Rocky"" Roque De La Fuente",Independent,12,6328
19,United States President,Benton,Alyson Kennedy,Independent,13,6328

In [353]:
# create "pct_county_vote" column for tn_2016_pres
tn_2016_pres['pct_county_vote']=round(tn_2016_pres['vote_count']/tn_2016_pres['sum_county_vote']*100,2)
tn_2016_pres

,officename,county,name,party,vote_count,sum_county_vote,pct_county_vote
0,United States President,Anderson,"""Rocky"" Roque De La Fuente",Independent,74,29881,0.25
1,United States President,Anderson,Alyson Kennedy,Independent,42,29881,0.14
2,United States President,Anderson,Donald J. Trump,Republican,19212,29881,64.30
3,United States President,Anderson,Gary Johnson,Independent,1034,29881,3.46
4,United States President,Anderson,Hillary Clinton,Democratic,9013,29881,30.16
...,...,...,...,...,...,...,...
884,United States President,Wilson,Mike Smith,Independent,207,56734,0.36
885,United States President,Wilson,Write-In - Darrell L. Castle,Independent,23,56734,0.04
886,United States President,Wilson,Write-In - Evan McMullin,Independent,280,56734,0.49
887,United States President,Wilson,Write-In - Laurence Kotlikoff,Independent,1,56734,0.00
888,United States President,Wilson,Write-In - Tom Hoefling,Independent,6,56734,0.01

In [354]:
# how many parties?
tn_2016_pres['party'].value_counts()

Independent    504
No party       195
Democratic      95
Republican      95
Name: party, dtype: int64

### Create "rep_vic_margin" column  with percent value difference for Republican compared to other parties for heat mapping

In [355]:
# create dataframe "tn_2016_margin"
tn_2016_pct_party_county=tn_2016_pres.loc[0:,['county','party','pct_county_vote']]
tn_2016_margin

,county,party_x,pct_county_vote,party_y,rep_pct_x,rep_vic_margin,party,rep_pct_y
0,Anderson,Independent,0.25,Republican,64.30,64.05,Republican,64.30
1,Anderson,Independent,0.14,Republican,64.30,64.16,Republican,64.30
2,Anderson,Republican,64.30,Republican,64.30,0.00,Republican,64.30
3,Anderson,Independent,3.46,Republican,64.30,60.84,Republican,64.30
4,Anderson,Democratic,30.16,Republican,64.30,34.14,Republican,64.30
...,...,...,...,...,...,...,...,...
884,Wilson,Independent,0.36,Republican,69.46,69.10,Republican,69.46
885,Wilson,Independent,0.04,Republican,69.46,69.42,Republican,69.46
886,Wilson,Independent,0.49,Republican,69.46,68.97,Republican,69.46
887,Wilson,Independent,0.00,Republican,69.46,69.46,Republican,69.46
888,Wilson,Independent,0.01,Republican,69.46,69.45,Republican,69.46

In [356]:
# create new dataframe with republican values only
tn_2016_rep_pct=tn_2016_pct_party_county[tn_2016_pct_party_county['party']== "Republican"].reset_index(drop=True)
tn_2016_rep_pct

        county       party  pct_county_vote
0     Anderson  Republican            64.30
1      Bedford  Republican            74.80
2       Benton  Republican            74.53
3      Bledsoe  Republican            77.66
4       Blount  Republican            71.72
..         ...         ...              ...
90       Wayne  Republican            85.98
91     Weakley  Republican            73.93
92       White  Republican            78.08
93  Williamson  Republican            64.19
94      Wilson  Republican            69.46

[95 rows x 3 columns]

In [357]:
# rename 'pct_county_vote' to 'rep_pct' to prepare for merge 
tn_2016_rep_pct=tn_2016_rep_pct.rename(columns={'pct_county_vote':'rep_pct'},inplace=False)
tn_2016_rep_pct.head(2)

     county       party  rep_pct
0  Anderson  Republican     64.3
1   Bedford  Republican     74.8

In [358]:
# use left merge to tn_2016_margin of tn_2016_rep_pct to fill in appropriate county values for Republican percentage
tn_2016_margin=tn_2016_margin.merge(tn_2016_rep_pct,on='county')
tn_2016_margin.head(20)

,county,party_x,pct_county_vote,party_y,rep_pct_x,rep_vic_margin,party_x,rep_pct_y,party_y,rep_pct
0,Anderson,Independent,0.25,Republican,64.30,64.05,Republican,64.30,Republican,64.30
1,Anderson,Independent,0.14,Republican,64.30,64.16,Republican,64.30,Republican,64.30
2,Anderson,Republican,64.30,Republican,64.30,0.00,Republican,64.30,Republican,64.30
3,Anderson,Independent,3.46,Republican,64.30,60.84,Republican,64.30,Republican,64.30
4,Anderson,Democratic,30.16,Republican,64.30,34.14,Republican,64.30,Republican,64.30
5,Anderson,Independent,0.63,Republican,64.30,63.67,Republican,64.30,Republican,64.30
6,Anderson,Independent,0.58,Republican,64.30,63.72,Republican,64.30,Republican,64.30
7,Anderson,No party,0.09,Republican,64.30,64.21,Republican,64.30,Republican,64.30
8,Anderson,No party,0.38,Republican,64.30,63.92,Republican,64.30,Republican,64.30
9,Bedford,Independent,0.16,Republican,74.80,74.64,Republican,74.80,Republican,74.80
10,Bedford,Independent,0.05,Republican,74.80,74.75,Republican,74.80,Republican,74.80
11,Bedford,Republican,74.80,Republican,74.80,0.00,Republican,74.80,Republican,74.80
12,Bedford,Independent,1.99,Republican,74.80,72.81,Republican,74.80,Republican,74.80
13,Bedford,Democratic,22.11,Republican,74.80,52.69,Republican,74.80,Republican,74.80
14,Bedford,Independent,0.49,Republican,74.80,74.31,Republican,74.80,Republican,74.80
15,Bedford,Independent,0.31,Republican,74.80,74.49,Republican,74.80,Republican,74.80
16,Bedford,No party,0.03,Republican,74.80,74.77,Republican,74.80,Republican,74.80
17,Bedford,No party,0.05,Republican,74.80,74.75,Republican,74.80,Republican,74.80
18,Benton,Independent,0.19,Republican,74.53,74.34,Republican,74.53,Republican,74.53
19,Benton,Independent,0.21,Republican,74.53,74.32,Republican,74.53,Republican,74.53

In [359]:
tn_2016_margin

,county,party_x,pct_county_vote,party_y,rep_pct_x,rep_vic_margin,party_x,rep_pct_y,party_y,rep_pct
0,Anderson,Independent,0.25,Republican,64.30,64.05,Republican,64.30,Republican,64.30
1,Anderson,Independent,0.14,Republican,64.30,64.16,Republican,64.30,Republican,64.30
2,Anderson,Republican,64.30,Republican,64.30,0.00,Republican,64.30,Republican,64.30
3,Anderson,Independent,3.46,Republican,64.30,60.84,Republican,64.30,Republican,64.30
4,Anderson,Democratic,30.16,Republican,64.30,34.14,Republican,64.30,Republican,64.30
...,...,...,...,...,...,...,...,...,...,...
884,Wilson,Independent,0.36,Republican,69.46,69.10,Republican,69.46,Republican,69.46
885,Wilson,Independent,0.04,Republican,69.46,69.42,Republican,69.46,Republican,69.46
886,Wilson,Independent,0.49,Republican,69.46,68.97,Republican,69.46,Republican,69.46
887,Wilson,Independent,0.00,Republican,69.46,69.46,Republican,69.46,Republican,69.46
888,Wilson,Independent,0.01,Republican,69.46,69.45,Republican,69.46,Republican,69.46

In [360]:
# add 'rep_vic_margin' column to show Republican margin over other parties per county
tn_2016_margin['repub_vic_margin']=tn_2016_margin['rep_pct']-tn_2016_margin['pct_county_vote']
tn_2016_margin

,county,party_x,pct_county_vote,party_y,rep_pct_x,rep_vic_margin,party_x,rep_pct_y,party_y,rep_pct,repub_vic_margin
0,Anderson,Independent,0.25,Republican,64.30,64.05,Republican,64.30,Republican,64.30,64.05
1,Anderson,Independent,0.14,Republican,64.30,64.16,Republican,64.30,Republican,64.30,64.16
2,Anderson,Republican,64.30,Republican,64.30,0.00,Republican,64.30,Republican,64.30,0.00
3,Anderson,Independent,3.46,Republican,64.30,60.84,Republican,64.30,Republican,64.30,60.84
4,Anderson,Democratic,30.16,Republican,64.30,34.14,Republican,64.30,Republican,64.30,34.14
...,...,...,...,...,...,...,...,...,...,...,...
884,Wilson,Independent,0.36,Republican,69.46,69.10,Republican,69.46,Republican,69.46,69.10
885,Wilson,Independent,0.04,Republican,69.46,69.42,Republican,69.46,Republican,69.46,69.42
886,Wilson,Independent,0.49,Republican,69.46,68.97,Republican,69.46,Republican,69.46,68.97
887,Wilson,Independent,0.00,Republican,69.46,69.46,Republican,69.46,Republican,69.46,69.46
888,Wilson,Independent,0.01,Republican,69.46,69.45,Republican,69.46,Republican,69.46,69.45

In [361]:
# Confirm negative numbers
tn_2016_margin['rep_vic_margin'].unique()

array([ 64.05,  64.16,   0.  ,  60.84,  34.14,  63.67,  63.72,  64.21,
        63.92,  74.64,  74.75,  72.81,  52.69,  74.31,  74.49,  74.77,
        74.34,  74.32,  73.22,  51.24,  74.36,  74.5 ,  74.48,  77.51,
        77.57,  75.62,  58.43,  77.27,  77.47,  77.62,  77.45,  71.56,
        71.58,  68.53,  48.54,  71.12,  71.24,  71.72,  71.62,  71.29,
        76.82,  76.88,  74.15,  58.71,  76.45,  76.62,  76.99,  76.91,
        76.38,  78.5 ,  78.56,  76.76,  60.82,  78.4 ,  78.42,  78.72,
        78.66,  75.25,  75.27,  73.41,  54.19,  74.85,  75.06,  75.34,
        75.23,  72.95,  52.28,  74.52,  74.67,  74.51,  80.01,  80.06,
        78.21,  63.77,  79.53,  79.89,  80.03,  79.85,  70.78,  70.86,
        68.03,  46.59,  70.32,  70.63,  70.89,  70.37,  78.01,  78.03,
        76.32,  58.99,  77.94,  77.91,  77.58,  79.94,  79.87,  78.3 ,
        63.03,  79.82,  79.84,  80.07,  73.25,  71.71,  49.11,  72.94,
        72.98,  80.57,  80.58,  79.  ,  64.4 ,  80.25,  80.52,  80.72,
        80.63,  72.03,  72.07,  69.6 ,  48.44,  71.88,  72.14,  71.92,
        72.18,  73.65,  73.72,  72.37,  49.64,  73.54,  73.63,  73.76,
        73.71,  77.3 ,  77.34,  75.65,  57.71,  77.06,  77.24,  77.38,
        77.28,  77.44,  33.78,  33.83,  30.09, -25.82,  32.96,  33.7 ,
        33.91,  33.95,  33.09,  74.21,  74.26,  72.67,  51.79,  73.65,
        73.93,  74.29,  78.05,  76.62,  58.67,  77.79,  77.97,  78.1 ,
        70.6 ,  70.67,  68.15,  45.52,  70.27,  70.46,  70.72,  70.55,
        70.75,  76.19,  76.23,  74.88,  55.21,  75.97,  76.13,  76.31,
        76.05,  67.21,  67.23,  65.96,  37.02,  66.99,  67.12,  67.2 ,
        67.06,  82.2 ,  82.15,  80.88,  67.34,  81.84,  82.19,  82.33,
        70.13,  70.2 ,  68.36,  43.64,  69.9 ,  70.08,  70.26,  70.15,
        70.29,  70.4 ,  70.44,  68.97,  43.63,  70.19,  70.35,  70.49,
        70.52,  70.31,  71.42,  71.46,  70.11,  45.37,  71.19,  71.55,
        71.49,  82.53,  82.59,  81.12,  68.33,  82.42,  82.39,  82.69,
        82.6 ,  78.59,  76.67,  60.83,  78.07,  78.47,  78.65,  78.71,
        78.52,  76.11,  76.28,  74.66,  55.37,  75.94,  76.07,  76.3 ,
        76.49,  76.5 ,  56.94,  76.18,  76.59,  76.22,  76.63,  55.19,
        51.47,  16.45,  54.52,  55.04,  55.21,  55.29,  54.55,  82.43,
        82.57,  80.73,  68.18,  82.03,  52.86,  52.93,  52.14,   7.92,
        52.73,  52.91,  52.95,  53.01,  80.38,  80.31,  79.18,  64.23,
        79.57,  80.05,  79.99,  80.08,  78.23,  63.26,  79.7 ,  80.11,
        80.13,  43.93,  43.94,  43.21, -10.21,  43.81,  79.52,  79.56,
        62.03,  79.27,  79.39,  79.64,  79.47,  73.31,  73.33,  71.73,
        49.79,  72.99,  73.24,  73.42,  72.63,  72.65,  70.83,  49.54,
        72.39,  72.7 ,  72.66,  72.61,  68.6 ,  68.75,  66.1 ,  41.54,
        68.5 ,  68.66,  68.68,  66.6 ,  41.42,  68.56,  68.6 ,  68.85,
        68.82,  72.42,  72.44,  71.07,  47.18,  72.08,  72.3 ,  72.21,
        77.29,  77.35,  74.86,  59.15,  76.87,  77.07,  77.43,  77.21,
        77.46,  82.06,  82.12,  80.68,  81.64,  82.09,  82.14,  58.32,
        58.4 ,  54.4 ,  23.73,  57.63,  57.98,  58.46,  58.53,  57.85,
        68.63,  68.83,  67.97,  39.59,  68.58,  60.22,  60.23,  59.31,
        22.6 ,  60.27,  60.34,  60.38,  79.15,  79.2 ,  77.55,  61.27,
        78.79,  79.05,  79.27,  79.26,  77.26,  77.39,  58.3 ,  76.65,
        77.37,  77.54,  77.76,  77.8 ,  76.17,  58.77,  77.56,  77.61,
        77.86,  77.59,  75.11,  75.2 ,  72.84,  54.26,  74.92,  74.96,
        75.28,  75.08,  75.26,  83.33,  83.41,  82.25,  69.17,  82.98,
        83.22,  83.43,  83.35,  55.77,  55.86,  54.24,  15.45,  55.6 ,
        55.74,  55.92,  55.97,  55.15,  70.68,  70.73,  68.82,  44.78,
        70.39,  70.65,  70.76,  71.3 ,  69.21,  46.54,  70.92,  71.14,
        71.35,  71.28,  67.15,  67.19,  64.68,  38.91,  66.82,  67.04,
        66.65,  67.28,  78.06,  78.22,  76.52,  59.61,  77.96,  78.14,
        78.28,  78.18,  78.32,  78.04,  59.7 ,  77.01,  77.49,  77.31,
        75.58,  57.55,  76.92,  78.06,  78.13,  59.6 ,  77.9 ,  77.93,
        78.17,  55.9 ,  55.97,  52.07,  18.47,  55.19,  55.83,  56.03,
        56.13,  55.71,  79.22,  77.03,  62.51,  78.88,  79.19,  80.96,
        81.02,  79.43,  65.43,  80.9 ,  80.81,  81.08,  77.72,  57.96,
        77.48,  77.76,  73.45,  73.5 ,  72.28,  49.99,  73.28,  73.57,
        73.41,  73.61,  73.59,  75.79,  75.76,  73.83,  54.99,  75.09,
        75.83,  77.2 ,  75.9 ,  56.78,  76.97,  78.11,  76.42,  58.97,
        77.77,  77.82,  69.69,  69.74,  67.05,  44.65,  69.  ,  69.51,
        69.71,  69.23,  69.83,  69.72,  78.  ,  76.29,  60.73,  77.97,
        77.81,  78.18,  77.44,  73.  ,  73.1 ,  70.53,  50.96,  72.88,
        72.97,  71.41,  71.51,  68.95,  47.11,  71.  ,  71.35,  71.59,
        71.43,  59.89,  59.93,  56.41,  25.88,  59.22,  59.71,  59.99,
        60.02,  59.46,  60.04,  84.71,  84.77,  83.73,  71.74,  84.56,
        84.46,  77.83,  77.92,  75.74,  59.5 ,  77.69,  77.74,  78.74,
        61.5 ,  78.26,  78.63,  78.8 ,  78.58,  78.83,  34.32,  34.37,
        32.42, -27.47,  33.89,  34.3 ,  34.48,  34.42,  34.07,  73.8 ,
        73.73,  51.17,  73.48,  73.62,  73.79,  73.87,  72.67,  70.15,
        49.86,  72.52,  72.69,  75.31,  72.55,  55.23,  74.86,  75.16,
        75.42,  69.97,  70.01,  67.17,  44.71,  69.59,  69.86,  71.85,
        69.95,  47.38,  71.64,  71.79,  71.93,  71.75,  66.23,  66.3 ,
        64.24,  36.61,  66.36,  66.42,  66.39,  78.63,  76.89,  61.28,
        78.08,  78.44,  78.76,  80.71,  80.76,  79.16,  64.69,  80.51,
        80.59,  80.86,  75.16,  75.2 ,  73.34,  52.96,  74.91,  67.6 ,
        44.12,  69.64,  69.79,  70.04,  69.85,  68.69,  68.74,  65.9 ,
        42.67,  67.89,  68.54,  68.78,  68.43,  85.79,  85.93,  85.02,
        73.74,  85.83,  85.78,  85.89,  85.84,  73.72,  73.85,  72.12,
        51.18,  73.61,  73.89,  73.58,  76.56,  59.3 ,  77.62,  77.68,
        78.04,  77.82,  64.07,  64.13,  59.94,  35.01,  63.7 ,  63.89,
        64.09,  64.19,  62.9 ,  64.18,  69.34,  69.31,  66.27,  44.1 ,
        68.64,  69.1 ,  69.42,  69.46,  69.45])

In [362]:
# join tn_2016_margin 'rep_vic_margin' column to tn_2016_pres
rep_pct=tn_2016_margin['repub_vic_margin']
tn_2016_pres=tn_2016_pres.join(rep_pct)
tn_2016_pres.head(3)

,officename,county,name,party,vote_count,sum_county_vote,pct_county_vote,repub_vic_margin
0,United States President,Anderson,"""Rocky"" Roque De La Fuente",Independent,74,29881,0.25,64.05
1,United States President,Anderson,Alyson Kennedy,Independent,42,29881,0.14,64.16
2,United States President,Anderson,Donald J. Trump,Republican,19212,29881,64.30,0.00

In [364]:
#zip_cbsa.to_excel(r'../data/zip_cbsa.xlsx',index=False)
tn_2016_pres.to_csv(r'../data/2016_election/tn_2016_pres.csv',index=False)

In [365]:
tn_2016_pres.to_excel(r'../data/2016_election/tn_2016_pres.xlsx',index=False)